### PR TITLE
Add zh-tw translations.

### PR DESCRIPTION
**Pull request by s8321414**
I added zh-tw translations, please review and merge it :smiley:

### CODE REVIEW

**Comment by elliottzheng** [comment]
Thanks for your devotion, as I'm rewriting CopyTranslator with Electron now, it will be very useful, I will add zh-tw to the supported language list. 
In the next version, I will make it possible for the user to add their own language support, without modifying the program. Would you like to help me to maintain the zh-tw translations?

**Comment by s8321414** [comment]
Yes! I am ready to do this :smiley:

**Comment by elliottzheng** [comment]
@s8321414 Hi, The  l10n system of copytranslator has been finished, you can refer to [https://github.com/elliottzheng/CopyTranslator/blob/phoenix/CONTRIBUTING.md#locale-settings-system](https://github.com/elliottzheng/CopyTranslator/blob/phoenix/CONTRIBUTING.md#locale-settings-system), welcome to join the gitter chat room at [https://gitter.im/CopyTranslator/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link](https://gitter.im/CopyTranslator/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link), so you can get notified before new version release. No need to hurry now, start to translate when I notify you or even after a new version is released is okay. Out of date locale file won't cause any error, the program will go back to English for the missing words.

**Comment by s8321414** [comment]
Well, so dist_locales will be a directory under this repo or another repo? BTW, I think you should use repo under CopyTranslator organation as main repo.

**Comment by elliottzheng** [comment]
dist_locales will be a directory under this repo. And as you see, CopyTranslator/CopyTranslator is the main repo now.

**Pull request merged**
